### PR TITLE
solution09 completed

### PR DESCRIPTION
**Pull request by Jayshgandhi**
Output for solution09

Enter a number to find:
56
Random generated array:[,89,96,5,20,86,19]
Output is:-100

### CODE REVIEW

**Comment by hockeyjudson** [comment]
Can you please attach , result for positive test case.

**Comment by Jayshgandhi** [comment]
Output 👍:
For element found condition:

Random generated array:[,4,8,9,7,3]
Element found
Output is:2

**Comment by hockeyjudson** [comment]
> Output 👍:
> For element found condition:
> 
> Random generated array:[,4,8,9,7,3]
> Element found
> Output is:2

You can still enhance the output. Still It need some effort to know what is the search element

**Review by hockeyjudson — APPROVED** [review]
LGTM

**Pull request merged**
